name: ez_credosafe_flutter
description: VS Corporate Lending mobile app (Phase 1 MVP)
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.2.1
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  file_picker: ^5.2.5
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  connectivity_plus: ^4.0.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  logger: ^2.0.2
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
